#ifndef ACCELERINE_SETTINGS_H
#define ACCELERINE_SETTINGS_H

#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480

#define HALF_HEIGHT SCREEN_HEIGHT / 2
#define HALF_WIDTH SCREEN_WIDTH / 2

#define SETTINGS_ENABLE 0xFFFFFFFF
#define SETTINGS_DISABLE 0x00000000

#define VSYNC SETTINGS_ENABLE

#endif  // ACCELERINE_SETTINGS_H
