#ifndef ACCELERINE_SETTINGS_H
#define ACCELERINE_SETTINGS_H

#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 448

#define HALF_HEIGHT SCREEN_HEIGHT / 2
#define HALF_WIDTH SCREEN_WIDTH / 2

#endif // ACCELERINE_SETTINGS_H
